In [1]:
import pandas as pd

In [3]:
temp = pd.read_excel("Book1.xlsx")

In [18]:
rng = pd.date_range(start = "2/1/2020",end = '30/4/2020',freq = "D")

In [19]:
len(rng)

90

In [20]:
temp["Date"]=rng

In [21]:
temp.set_index(["Date"])

            max  min
Date
2020-02-01   18    9
2020-02-02   19    9
2020-02-03   18    9
2020-02-04   19   10
2020-02-05   21   11
2020-02-06   22   12
2020-02-07   19   15
2020-02-08   16   13
2020-02-09   15   11
2020-02-10   14   10
2020-02-11   18   10
2020-02-12   20    9
2020-02-13   24   10
2020-02-14   20   13
2020-02-15   21   11
2020-02-16   20   12
2020-02-17   19   14
2020-02-18   19   11
2020-02-19   17   10
2020-02-20   19   11
2020-02-21   20   10
2020-02-22   17   12
2020-02-23   18   11
2020-02-24   16   10
2020-02-25   20   11
2020-02-26   22   12
2020-02-27   25   13
2020-02-28   26   16
2020-02-29   21   14
2020-03-01   19   12
...         ...  ...
2020-04-01   24   14
2020-04-02   23   10
2020-04-03   24   10
2020-04-04   24   10
2020-04-05   25   10
2020-04-06   26   11
2020-04-07   29   12
2020-04-08   25   11
2020-04-09   26   14
2020-04-10   30   12
2020-04-11   29   12
2020-04-12   26   11
2020-04-13   26   12
2020-04-14   28   14
2020-04-15   30   12
2020-04-16   28   15
2020-04-17   30   14
2020-04-18   31   15
2020-04-19   31   16
2020-04-20   32   16
2020-04-21   32   15
2020-04-22   32   15
2020-04-23   31   16
2020-04-24   32   16
2020-04-25   31   16
2020-04-26   33   18
2020-04-27   33   17
2020-04-28   34   15
2020-04-29   30   13
2020-04-30   29   12

[90 rows x 2 columns]

In [22]:
data = pd.read_csv("combined_csv.csv")

In [23]:
from matplotlib import pyplot
def determine_country(country):
    data_country = pd.DataFrame(data.loc[[country]])
    data_country = data_country.set_index("Last Update")
    data_country.to_csv("{0}_1603.csv".format(country))
    %matplotlib inline
    data_country.Confirmed.plot(kind="line")
    return data_country

In [37]:
data.set_index(["Country/Region"])
data.head()

,Confirmed,Country/Region,Deaths,Last Update,Latitude,Longitude,Province/State,Recovered
0,1.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Anhui,NaN
1,14.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Beijing,NaN
2,6.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Chongqing,NaN
3,1.0,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Fujian,NaN
4,NaN,Mainland China,NaN,1/22/2020 17:00,NaN,NaN,Gansu,NaN

In [34]:
egypt_data = determine_country("Egypt")

KeyError: "None of [['Egypt']] are in the [index]"

In [39]:
temp.to_csv("temp.csv")